version: '3'

volumes:
  directus_db:
  directus_data:

services:
  directus:
    container_name: directus
    image: directus/directus:latest
    depends_on:
      - directus_db
    # ports:
    #   - 8055:8055  # use proxy servers
    volumes:
      - directus_data:/directus
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}

      DB_CLIENT: pg
      DB_PORT: 5432
      DB_HOST: directus_db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_NAME}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASS}

  directus_db:
    container_name: directus_db
    image: postgres:14-alpine
    volumes:
      - directus_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
