version: '3'

volumes:
  directus_db:
  directus_data:

networks:
  directus:
  proxy:
    external: true

services:
  directus:
    container_name: 'directus'
    image: 'directus/directus:latest'
    depends_on:
      - directus_db
      - directus_cache
    # ports:
    #   - 8055:8055  # use revers proxy to access this port
    volumes:
      - 'directus_data:/directus'
    networks:
      - directus
      - proxy
    environment:
      FLOWS_EXEC_ALLOWED_MODULES: array:moment,uuid

      KEY: '${KEY}'
      SECRET: '${SECRET}'

      DB_CLIENT: 'postgres'
      DB_PORT: '5432'
      DB_HOST: 'directus_db'
      DB_DATABASE: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASS}'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://directus_cache:6379'

      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASS}'

  directus_db:
    container_name: 'directus_db'
    image: 'postgis/postgis:latest'
    networks:
      - directus
    volumes:
      - directus_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  directus_cache:
    container_name: directus_cache
    image: redis:latest
    networks:
      - directus
