---
version: "3"

volumes:
  directus-db:
  directus-cache:

networks:
  directus:
  proxy:
    external: true

services:

  directus-cache:
    container_name: directus-cache
    image: redis:latest
    networks:
      - directus
    volumes:
      - directus-cache:/data

  directus-db:
    container_name: directus-db
    image: postgis/postgis:latest
    depends_on:
      - directus-cache
    networks:
      - directus
    volumes:
      - "directus-db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  directus:
    container_name: directus
    image: directus/directus:10.9.3
    depends_on:
      - directus-cache
      - directus-db
    ports: [8055:8055] ## Disable in production
    volumes:
      - "./data/uploads:/directus/uploads"
      - "./data/database:/directus/database"
    networks:
      - directus
      - proxy
    env_file: .env
    environment:
      DB_CLIENT: pg
      DB_CONNECTION_STRING: pg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@directus-db/${POSTGRES_DB}
      REDIS_HOST: directus-cache
      WEBSOCKETS_ENABLED: true
