version: "3"
volumes:
  directus_db:
  directus_dir:
networks:
  directus:
  proxy:
    external: true
services:
  directus_cache:
    container_name: directus_cache
    image: redis:latest
    networks: [directus]
  directus_db:
    container_name: directus_db
    image: postgis/postgis:latest
    networks: [directus]
    volumes: ["directus_db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  directus:
    container_name: directus
    image: directus/directus:latest
    depends_on: [directus_db, directus_cache]
    # ports:
    #   - 8055:8055  # use revers proxy to access this port
    volumes: ["directus_dir:/directus"]
    networks: [directus, proxy]
    environment:
      FLOWS_EXEC_ALLOWED_MODULES: array:moment,uuid
      # App URL
      PUBLIC_URL: ${PUBLIC_URL}
      # App Keys
      KEY: ${KEY}
      SECRET: ${SECRET}
      # Admin Creds
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      # Emails Sender
      EMAIL_TRANSPORT: smtp
      EMAIL_VERIFY_SETUP: true
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      # Database
      DB_CLIENT: pg
      # DB_PORT: "5432"
      # DB_HOST: directus_db
      # DB_USER: ${DB_USER}
      # DB_DATABASE: ${DB_DATABASE}
      # DB_PASSWORD: ${DB_PASSWORD}
      DB_CONNECTION_STRING: pg://${DB_USER}:${DB_PASSWORD}@directus_db/${DB_DATABASE}
      # Cache
      CACHE_ENABLED: true
      CACHE_STORE: redis
      CACHE_TTL: 1m
      CACHE_AUTO_PURGE: false
      REDIS_HOST: directus_cache
      # CACHE_VALUE_MAX_SIZE: 250MB
