---
version: '3'

networks:
  proxy:
    external: true
  nginx:
    driver: bridge

volumes:
  nginx_db:
  nginx_data:
  nginx_letsencrypt:

services:
  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - nginx
      - proxy
    environment:
      DB_MYSQL_HOST: nginx_db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: nginx
      DB_MYSQL_USER: nginx
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - 'nginx_data:/data'
      - 'nginx_letsencrypt:/etc/letsencrypt'

  nginx_db:
    container_name: nginx_db
    image: jc21/mariadb-aria:latest
    restart: always
    environment:
      MYSQL_DATABASE: nginx
      MYSQL_USER: nginx
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - nginx
    volumes:
      - 'nginx_db:/var/lib/mysql'
