---
version: '3'

volumes:
  portainer_data:

networks:
  proxy:
    external: true

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports: [9000:9000] ## Disable in production
    networks: [proxy]
    security_opt: [no-new-privileges:true]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
