---
version: '3'

x-logging: &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'

volumes:
  portainer_data:

networks:
  proxy:
    external: true

services:
  portainer:
    <<: *x-logging
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    # ports: [9000:9000] ## Disable in production
    networks: [proxy]
    security_opt: [no-new-privileges:true]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
