---
version: "3"

# For Nginx Proxy Manager
# domain: matomo.mydomain.com
# scheme: http 
# forward hostname/ip: matomo (container_name)
# forward port: 80
# enable: Cache Assests, Block Common Exploits, Websockets support
# SSL: matomo.mydomain.com 
# Enable: Force SSL, HTTP/2 Support, HSTS Enabled

networks:
  proxy:
    external: true

volumes:
  matomo:
  matomo-maria:

services:
  matomo:
    container_name: matomo
    image: matomo:5.0.1
    restart: always
    networks:
      - proxy
    volumes:
      - matomo:/var/www/html
    environment:
      PHP_MEMORY_LIMIT: 750M
      MATOMO_DATABASE_HOST: matomo-maria
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: ${MYSQL_USER}
      MATOMO_DATABASE_DBNAME: ${MYSQL_DATABASE}
      MATOMO_DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  matomo-maria:
    image: mariadb:11.3-rc
    container_name: matomo-maria
    command: --max-allowed-packet=64MB
    restart: always
    networks:
      - proxy
    volumes:
      - matomo-maria:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
      MARIADB_DISABLE_UPGRADE_BACKUP: 1
