---
version: "3"

# For Nginx Proxy Manager
# domain: matomo.mydomain.com
# scheme: http 
# forward hostname/ip: matomo (container_name)
# forward port: 80
# enable: Cache Assests, Block Common Exploits, Websockets support
# SSL: matomo.mydomain.com 
# Enable: Force SSL, HTTP/2 Support, HSTS Enabled

networks:
  proxy:
    external: true

volumes:
  matomo:
  matomo-db:

services:

  matomo-db:
    image: mariadb:10.11
    container_name: matomo-db
    command: --max-allowed-packet=64MB
    restart: always
    networks:
      - proxy
    volumes:
      - matomo-db:/var/lib/mysql
    environment:
      MYSQL_USER: matomo
      MYSQL_DATABASE: matomo
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
      MARIADB_DISABLE_UPGRADE_BACKUP: 1

  matomo:
    container_name: matomo
    image: matomo:5.0.1
    restart: always
    links:
      - matomo-db
    networks:
      - proxy
    volumes:
      - ./data:/var/www/html
    depends_on:
      - matomo-db
    environment:
      PHP_MEMORY_LIMIT: 750M
      MATOMO_DATABASE_HOST: matomo-db
      ## Keep Disabled: Conflicts with Enviroment Variables Plugin
      # MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_DBNAME: matomo
      MATOMO_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
